services:
  - type: web
    name: stock-monitor-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: stock-monitor-db
          property: connectionString

databases:
  - name: stock-monitor-db
    databaseName: stockmonitor
    user: stockmonitor
    plan: free
